name: ci-main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write
  security-events: write
  attestations: write
  packages: write

jobs:
  pipeline:
    uses: steinshei/platform-cicd/.github/workflows/reusable-ci.yml@v1
    with:
      service_name: sample-service
      context_dir: apps/sample-service
      dockerfile: apps/sample-service/Dockerfile
      run_tests: true
    secrets: inherit

  update-dev-gitops:
    needs: [pipeline]
    uses: steinshei/platform-cicd/.github/workflows/reusable-deploy-dev.yml@v1
    with:
      service_name: sample-service
      values_file: gitops/environments/dev/sample-service-values.yaml
      image_tag: ${{ github.sha }}
      skip_if_deploy_commit: true
    secrets:
      ci_bot_token: ${{ secrets.CI_BOT_TOKEN }}
