name: promote

on:
  workflow_dispatch:
    inputs:
      service:
        description: Service name
        required: true
        default: sample-service
      image_tag:
        description: Git SHA tag promoted from staging to prod
        required: true

jobs:
  promote:
    uses: steinshei/platform-cicd/.github/workflows/reusable-promote.yml@v1
    with:
      service: ${{ github.event.inputs.service }}
      image_tag: ${{ github.event.inputs.image_tag }}
      staging_values_file: gitops/environments/staging/${{ github.event.inputs.service }}-values.yaml
      prod_values_file: gitops/environments/prod/${{ github.event.inputs.service }}-values.yaml
